# Generated by Django 6.0.4 on 2026-04-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin_mitra',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_nelayan',
        ),
        migrations.AddField(
            model_name='user',
            name='is_new_oauth_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('umum', 'Masyarakat Umum'), ('nelayan', 'Nelayan'), ('tps', 'Pengelola TPS'), ('admin', 'Admin')], default='umum', max_length=10),
        ),
    ]
