# Generated by Django 6.0.4 on 2026-04-21 06:57

import django.db.models.deletion
import features.users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_admin_mitra_remove_user_is_nelayan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPSProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tps', models.CharField(max_length=255)),
                ('alamat', models.TextField()),
                ('kecamatan', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('kapasitas_kg_hari', models.FloatField(default=100.0)),
                ('harga_per_kg', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'tps'}, on_delete=django.db.models.deletion.CASCADE, related_name='tps_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_requested', models.CharField(choices=[('nelayan', 'Nelayan'), ('tps', 'Pengelola TPS')], max_length=10)),
                ('doc_type', models.CharField(choices=[('ktp', 'KTP'), ('kartu_nelayan', 'Kartu Nelayan / Surat Keterangan'), ('nib', 'NIB (Nomor Induk Berusaha)'), ('foto_lokasi_tps', 'Foto Lokasi TPS')], max_length=30)),
                ('file', models.ImageField(upload_to=features.users.models.verification_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
                ('rejection_note', models.TextField(blank=True, help_text='Diisi Admin jika dokumen ditolak, agar user tahu alasannya.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
