# Generated by Django 6.0.4 on 2026-04-21 07:53

import django.db.models.deletion
import features.submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_tpsprofile_verificationdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_sampah', models.ImageField(upload_to=features.submissions.models.submission_upload_path)),
                ('perceptual_hash', models.CharField(db_index=True, help_text='pHash dari foto. Dipakai untuk deteksi duplikat.', max_length=64)),
                ('ai_estimation', models.JSONField(default=dict)),
                ('final_weight', models.JSONField(blank=True, default=dict, help_text='Diisi oleh TPS setelah penimbangan fisik.')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Validasi TPS'), ('validated', 'Sudah Divalidasi TPS'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_submissions', to='users.tpsprofile')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'nelayan'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
