# Generated by Django 6.0.4 on 2026-04-21 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_reward', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True)),
                ('koin_dibutuhkan', models.PositiveIntegerField()),
                ('stok', models.PositiveIntegerField(default=0, help_text='0 = tidak terbatas.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['koin_dibutuhkan'],
            },
        ),
        migrations.CreateModel(
            name='RedemptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koin_spent', models.PositiveIntegerField(help_text='Snapshot koin saat transaksi — harga bisa berubah di catalog.')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Proses'), ('success', 'Berhasil'), ('failed', 'Gagal')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='rewards.rewardcatalog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positif untuk earn, negatif untuk redeem.')),
                ('transaction_type', models.CharField(choices=[('earn', 'Koin Masuk (Setoran Sampah)'), ('redeem', 'Koin Keluar (Penukaran Hadiah)')], max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('ref_submission_id', models.IntegerField(blank=True, null=True)),
                ('ref_redemption_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
